name: Continuous Integration

on: [push]

jobs:
    test:
      runs-on: ubuntu-latest
      container:
        image: docker://conuforecast
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Black
        run: black --check ConuForecast
      - name: Flake8 
        run: flake8 ConuForecast
      - name: Unit Tests
        run: |
          pip install -r docker/requirements.txt
          pytest ConuForecast
        env:
          MLFLOW_TRACKING_URI: /experiments
          MLFLOW_ARTIFACT_LOCATION: 